### PR TITLE
Proposed revision to GeoSPARQL to LOCN mapping

### PR DESCRIPTION
**Pull request by andrea-perego**
Summary of proposed revisions:
- Make `geo:Geometry` a subclass of `locn:Geometry`
- Editorial changes

### CODE REVIEW

**Comment by situx** [comment]
Thank you for the corrections.
The alignments have also been formalized in TTL. 
Would you mind correcting those as well in your pull request?
The folder is 1.1/alignments.

**Comment by andrea-perego** [comment]
> Thank you for the corrections. The alignments have also been formalized in TTL. Would you mind correcting those as well in your pull request? The folder is 1.1/alignments.

Thanks, @situx . `.ttl` file updated via commit https://github.com/opengeospatial/ogc-geosparql/pull/313/commits/4eb4277d0d250df9d58e0768f72eed915494f4c1

**Comment by andrea-perego** [comment]
@situx , @nicholascar , noting no additional comments, I'm going to make this PR ready for review.

**Review by situx — APPROVED** [review]

**Review by nicholascar — APPROVED** [review]
Thanks @andrea-perego for the fixes and @situx for the review!

**Pull request merged**
