### PR TITLE
1.1 improve funcrules

### LINKED ISSUE #51: Improve the GeoSPARQL vocabularies
The OGC publishes vocabularies from GeoSPARQL separately, see this dev publication of the _GeoSPARQL Functions Register_ Vocab:

http://defs-dev.opengis.net/vocprez/object?uri=http://www.opengis.net/def/function/geosparql

There are a number of problems with this vocabulary from a _Vocabulary Best Practice_ (my informal assessment of it) point-of-view:

* duplicate prefLabels
    * Functions `sfContains` & `ehContains` have the prefLabel "contains"
* multiple, different objects within a single hierarchy
    * both GeoSPARQL `Rule` and `Function` are listed but not differentiated in the hierarchy - they are in separate Collections
    * the vocabulary is called _GeoSPARQL Functions Register_  but contains more than `Functions`
* lack of vocabulary-level metadata
    * individual Concepts have good metadata but the vocab as a whole doesn't
    * the Collections don't have any metadata to describe the purpose/logic of the Collection

I propose that changes to the vocabs to address these issues be part of the _Best Practice_ publication of GeoSPARQL 1.1

### PR DESCRIPTION
**Pull request by nicholascar**
Improves the Functions & Rules vocabulary in line with points raised in Issue #51.

I have not addressed the issue of repeated `prefLabel` values as now the things with repeated values are listed in separate Collections (and also all-term Collections) so they should be easier to differentiate.

Closes #51

### CODE REVIEW

**Comment by FransKnibbe** [comment]
Sorry Nick, I have caught CoVID-19 a while ago, which for the moment has left me less capable of doing anything useful. Could you ask someone else to review? I hope I'm back soon.

**Review by dr-shorthair — COMMENTED** [review]
I don't know RIF so can't evaluate this properly. 
The other files seem fine though.

**Comment by nicholascar** [comment]
@mperry455 @lvdbrink bringing you both in as reviewers here since Simon doesn't know RIF and Fans is unavailable. I have also put the file here to the W3C RIF Community Group for review.

**Comment by dr-shorthair** [comment]
Though note that I am very interested in following this. RIF might be easier applied to OWL-Time - see https://github.com/w3c/sdw/issues/1236

**Comment by mperry455** [comment]
I think this is good to merge as long as rules.rifps is updated based on the discussion in #76

**Pull request merged**
