### PR TITLE
Spatial Aggregate fix

### PR DESCRIPTION
**Pull request by situx**
This pull request works on fixing issues concerning spatial aggregate function definitions referring to #101 and #105

Current issues:

- We have a union function with differing signatures. One is currently renamed to union2. Should we maybe define a function with two different possible signatures?

### CODE REVIEW

**Review by nicholascar — APPROVED** [review]

**Comment by nicholascar** [comment]
Looks good, although I see you have a merge to deal with!

**Comment by situx** [comment]
Yes I will deal with the merge conflict. However, my concern is still the union2 function. Is that really a good name? I guess we cannot assign two function signatures to one URI, can we?

**Comment by nicholascar** [comment]
OK, just a couple more changes actually:

1.
```turtle
skos:prefLabel "GeoSPARQL Spatial Aggregate Functions Register"
```
remove word "register" as it implies a certain type of vocab (one with statuses for each element):
```turtle
skos:prefLabel "GeoSPARQL Spatial Aggregate Functions"
```

2. Call the function `safuncs:minBoundingCircle` just `safuncs:boundingCircle` as that will better match bounding Box (i.e. we don't call it min bounding box).

3.
```turtle
skos:definition "A spatial aggregate function that calculates a centroid out of a list of vector geometries."@en ;
```
better English:
```turtle
skos:definition "A spatial aggregate function that calculates a centroid of a set of geometries."@en ;
```
and we don't need the qualifier "vector geometries" as we've not used that anywhere else

4.
```turtle
skos:definition "A spatial aggregate function that calculates a concatenated line out of a list of lines."@en ;
```
better English: 
```turtle
skos:definition "A spatial aggregate function that calculates a concatenated line of a set of lines."@en ;
```
5.
```turtle
skos:definition "A spatial aggregate function that calculates the concave hull of a list of vector geometries."@en ;
```
better English:
```turtle
skos:definition "A spatial aggregate function that calculates the concave hull of a set of geometries."@en ;
```
7.
```turtle
skos:definition "A spatial aggregate function that calculates the mininum bounding circle of a given set of geometries."@en ;
```
typo, consistent wording & better English:
```turtle
skos:definition "A spatial aggregate function that calculates the minimum bounding circle of set of geometries."@en ;
```
8.
```turtle
skos:definition "A spatial aggregate function that calculates the union out of a list of vector geometries."@en ;
```
better English:

```turtle
skos:definition "A spatial aggregate function that calculates the union of a set of geometries."@en ;
```

Finally, for the`union2` function name: I actually think `union2` is fine as it's obvious that it is "just" a union function but different from another "just" union function. If you call it something like `aggregateUnion` or `agUnion` or whatever, it looks like it's doing something a bit different, i.e. you can't mistake `2` for indicating any purpose other than identity separation of the function. There are loads of examples in well known software of `function` & `function2` which does the same thing but faster/better etc.

**Comment by situx** [comment]
Ok done

**Comment by nicholascar** [comment]
OK, just waiting for a second review from either @dr-shorthair or @FransKnibbe

**Review by dr-shorthair — APPROVED** [review]
Noting, however, that X, Y Z are the typical mathematical notation for 3 dimensions, which may go by other names depending on the CRS (lat/lon/easting/northing/elevation/depth) - does there need to be an informative note added to this effect?

**Comment by situx** [comment]
I think we could add a note for that. In general, I would assume that e.g. by X we mean the first dimension irrespective of the axis order defined by the CRS.

**Pull request merged**
