### PR TITLE
Add Collection classes

### LINKED ISSUE #148: Add geo:FeatureCollection
to support OGC API  - as discussed with @nicholascar

### PR DESCRIPTION
**Pull request by dr-shorthair**
Fixes #148

### CODE REVIEW

**Comment by situx** [comment]
@dr-shorthair Would it make sense to also include query functions for GeometryN and NumGeometries from the Simple Features for SQL if we included GeometryCollections in the spec?

**Comment by dr-shorthair** [comment]
Yes - I had only chased down (most of?) the static aspects.

**Comment by situx** [comment]
Okay, I can add another pull request adding those functions, as I am currently updating the comparison table for SQL.

**Review by situx — APPROVED** [review]

**Review by nicholascar — APPROVED** [review]
Looks good. The PR is in draft but it should be merged in and then I'll follow-up with additions to the Annex B: Examples

**Comment by nicholascar** [comment]
@dr-shorthair are you going to merge this or add new things to it, since it's still in draft? If you were going to add bits, consider the Annex B: Examples.

**Comment by dr-shorthair** [comment]
I'm waiting for consensus on #148 - a couple of open questions there.

**Comment by nicholascar** [comment]
Based on discussion in #148, can this PR be either brought out of draft or withdrawn by early to mid July? This is so we can finalise standing PRs and submit GeoSPARQL 1.1 for wider review at the end of July.

**Comment by nicholascar** [comment]
@dr-shorthair can you please move this out of draft given the status of conversation in #148?

**Pull request merged**
