### PR TITLE
re-mapping to BFO2020 due to feedback

### PR DESCRIPTION
**Pull request by nicholascar**
Due to BFO authors pointing to BFO 2020 as the best target

### CODE REVIEW

**Comment by nicholascar** [comment]
image
image

**Review by situx — APPROVED** [review]
The mapping looks ok to me. However, it again somehow underlines to me that in GeoSPARQL 1.2, we should give some guidance as to how we expect people to deal with spatiotemporal data.

**Comment by dr-shorthair** [comment]
Here's the BFO class hierarchy from ISO/IEC 21838-2:2021 for reference
image

**Review by dr-shorthair — APPROVED** [review]

**Comment by nicholascar** [comment]
Yes, I think that GeoSPARQL's lack of temporal handing is really shown up here! We do need to write about it in 1.1 and then to take it very seriously for 1.2.

**Review by mperry455 — APPROVED** [review]

**Pull request merged**
