### PR TITLE
Shacl annex

### LINKED ISSUE #230: Need to add guidance for how to validate GeoSPARQL Shapes
We have lots of instructions on RIF rules, but limited instruction on SHACL Shapes, and how to validate them.

Let's add this guidance.

### PR DESCRIPTION
**Pull request by situx**
This is a draft for the SHACL annex. Feel free to contribute further.

Closes #230

### CODE REVIEW

**Comment by situx** [comment]
I finished the SHACL annex and in this process also added labels to every requirement in the spec.
Also, I corrected the names of hasMetricSpatialAccuracy and hasMetricSpatialResolution in the SHACL rules as they were mistaken.
What is left to do:

- [ ] Remove two SHACL shapes as agreed upon
- [ ] Renumbering SHACL shapes and update the annex
- [ ] Possibly adding a SHACL example

**Comment by dr-shorthair** [comment]
Well done Timo.

**Review by nicholascar — APPROVED** [review]
I made some very small changes to the text

**Comment by situx** [comment]
Renumbered all SHACL shapes and updated the annex

**Review by mperry455 — APPROVED** [review]
Approving, but I would still like to see S1-b-hasGeometry-hasSerialization-sub and S21-geometryClass-hasSerialization-sub removed because of entailment-related issues.

**Comment by situx** [comment]
@mperry455 Done

**Pull request merged**
