### PR TITLE
Add an ontology overview Figure

### PR DESCRIPTION
**Pull request by nicholascar**
and tidy the annotations of other figures.

See the new Figure rendered in place for review at https://raw.githack.com/opengeospatial/ogc-geosparql/ontology-diagrams/1.1/spec/spec-ont-fig.html#_core

### CODE REVIEW

**Comment by mperry455** [comment]
Looks good Nick, but I believe those Simple Features, Egenhofer and RCC8 relations are defined on SpatialObject rather than Feature.

**Comment by situx** [comment]
@nicholascar I think you could add the rdfs:subClassOf relations of the collection classes to make the diagram complete

**Comment by nicholascar** [comment]
> Looks good Nick, but I believe those Simple Features, Egenhofer and RCC8 relations are defined on SpatialObject rather than Feature.

Oops, I've fixed that.

> I think you could add the rdfs:subClassOf relations of the collection classes to make the diagram complete.

I've added those.

**Comment by nicholascar** [comment]
> I would put ogc:geomLiteral there because it is also used in the standard

Done

**Comment by nicholascar** [comment]
OK, I think I've addressed the issues identified.

**Review by situx — APPROVED** [review]
Looking good now

**Review by mperry455 — APPROVED** [review]
Looks good to me.

**Pull request merged**
