### PR TITLE
Update validator.ttl

### LINKED ISSUE #177: Decide on SHACL shape about serializations
This issue is to discuss SHACL validation shape number 1.

I encourage everyone to add pro/con arguments to add to this post so that we can make an informed decision.
Please edit this post whenever needed:

1 serialization per Geometry instance:
- The coordinate reference system is the same
- There are no conflicts concerning a differing accuracy a.s.o. because only one serialization per geometry exists

Many serializations per Geometry:
- The serializations need to be equivalent, but not equal. For example, they could be in different CRS according to literal restrictions (GeoJSON only allows WGS84 for example)
-  The serializations could have a differing accuracy

Please add more arguments for either side that I missed

### PR DESCRIPTION
**Pull request by FransKnibbe**
Remove shape 1a; make shapes 1 and 3 work on solo Geometries too. Solves[ issue 177](https://github.com/opengeospatial/ogc-geosparql/issues/177).

Fixes #177

### CODE REVIEW

**Review by situx — CHANGES_REQUESTED** [review]
I think your changes work in general, but I think we would also need to update the table in the GeoSPARQL Annex. Was that part of your pull request or should we create a different pull request for that?

**Comment by jabhay** [comment]
- [ ] Update table in Appendix E to reflect changes to shapes.

**Review by nicholascar — APPROVED** [review]
I'm approving and merging but will submit a follow-up PR to apply some further fixes

**Comment by FransKnibbe** [comment]
> I'm approving and merging but will submit a follow-up PR to apply some further fixes

Hi @nicholascar: Will that follow-up include an update of Annex D.3?

**Pull request merged**
